/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/suzanne_2.gltf
*/

import React, { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

import * as THREE from 'three';

export function Model(props) {
  const { nodes, materials } = useGLTF('/suzanne_2.gltf');

  const rockTextureProps = useTexture({
    map: '/texture_rock/CliffJagged004_COL_VAR1_1K.jpg',
    // displacementMap: '/texture_rock/CliffJagged004_DISP_VAR1_1K.jpg',
    normalMap: '/texture_rock/CliffJagged004_NRM_1K.jpg',
    roughnessMap: '/texture_rock/CliffJagged004_GLOSS_1K.jpg',
    aoMap: '/texture_rock/CliffJagged004_AO_1K.jpg',
  });

  rockTextureProps.map.repeat.set(3, 3);
  rockTextureProps.normalMap.repeat.set(3, 3);
  rockTextureProps.roughnessMap.repeat.set(3, 3);
  rockTextureProps.aoMap.repeat.set(3, 3);

  rockTextureProps.map.wrapS =
    rockTextureProps.map.wrapT =
    rockTextureProps.normalMap.wrapS =
    rockTextureProps.normalMap.wrapT =
    rockTextureProps.roughnessMap.wrapS =
    rockTextureProps.roughnessMap.wrapT =
    rockTextureProps.aoMap.wrapS =
    rockTextureProps.aoMap.wrapT =
      THREE.RepeatWrapping;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry}>
        <meshStandardMaterial {...rockTextureProps} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/suzanne_2.gltf');
