/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/suzanne_2.gltf
*/

import React, { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

import * as THREE from 'three';

import { useTextureContext } from '../textureContext';

export function Model(props) {
  const { nodes, materials } = useGLTF('/suzanne_2.gltf');

  const { texture } = useTextureContext();

  // console.log('texture', texture)

  const { map, normalMap, roughnessMap, aoMap } = texture;

  const textureProps = useTexture({
    map,
    normalMap,
    roughnessMap,
    aoMap,
  });

  textureProps.map.repeat.set(3, 3);
  textureProps.normalMap.repeat.set(3, 3);
  textureProps.roughnessMap.repeat.set(3, 3);
  textureProps.aoMap.repeat.set(3, 3);

  textureProps.map.wrapS =
    textureProps.map.wrapT =
    textureProps.normalMap.wrapS =
    textureProps.normalMap.wrapT =
    textureProps.roughnessMap.wrapS =
    textureProps.roughnessMap.wrapT =
    textureProps.aoMap.wrapS =
    textureProps.aoMap.wrapT =
      THREE.RepeatWrapping;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry}>
        <meshStandardMaterial {...textureProps} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/suzanne_2.gltf');
